/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppStockExportsRouteImport } from './routes/_app/stock-exports'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRecipesRouteImport } from './routes/_app/recipes'
import { Route as AppKiotvietRouteImport } from './routes/_app/kiotviet'
import { Route as AppIngredientsRouteImport } from './routes/_app/ingredients'
import { Route as AppIngredientUsageRouteImport } from './routes/_app/ingredient-usage'
import { Route as AppImportOrdersRouteImport } from './routes/_app/import-orders'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAuditLogsRouteImport } from './routes/_app/audit-logs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStockExportsRoute = AppStockExportsRouteImport.update({
  id: '/stock-exports',
  path: '/stock-exports',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppKiotvietRoute = AppKiotvietRouteImport.update({
  id: '/kiotviet',
  path: '/kiotviet',
  getParentRoute: () => AppRoute,
} as any)
const AppIngredientsRoute = AppIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AppRoute,
} as any)
const AppIngredientUsageRoute = AppIngredientUsageRouteImport.update({
  id: '/ingredient-usage',
  path: '/ingredient-usage',
  getParentRoute: () => AppRoute,
} as any)
const AppImportOrdersRoute = AppImportOrdersRouteImport.update({
  id: '/import-orders',
  path: '/import-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/import-orders': typeof AppImportOrdersRoute
  '/ingredient-usage': typeof AppIngredientUsageRoute
  '/ingredients': typeof AppIngredientsRoute
  '/kiotviet': typeof AppKiotvietRoute
  '/recipes': typeof AppRecipesRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/stock-exports': typeof AppStockExportsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/import-orders': typeof AppImportOrdersRoute
  '/ingredient-usage': typeof AppIngredientUsageRoute
  '/ingredients': typeof AppIngredientsRoute
  '/kiotviet': typeof AppKiotvietRoute
  '/recipes': typeof AppRecipesRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/stock-exports': typeof AppStockExportsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/import-orders': typeof AppImportOrdersRoute
  '/_app/ingredient-usage': typeof AppIngredientUsageRoute
  '/_app/ingredients': typeof AppIngredientsRoute
  '/_app/kiotviet': typeof AppKiotvietRoute
  '/_app/recipes': typeof AppRecipesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/stock-exports': typeof AppStockExportsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/dashboard'
    | '/import-orders'
    | '/ingredient-usage'
    | '/ingredients'
    | '/kiotviet'
    | '/recipes'
    | '/reports'
    | '/roles'
    | '/stock-exports'
    | '/suppliers'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/dashboard'
    | '/import-orders'
    | '/ingredient-usage'
    | '/ingredients'
    | '/kiotviet'
    | '/recipes'
    | '/reports'
    | '/roles'
    | '/stock-exports'
    | '/suppliers'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/audit-logs'
    | '/_app/dashboard'
    | '/_app/import-orders'
    | '/_app/ingredient-usage'
    | '/_app/ingredients'
    | '/_app/kiotviet'
    | '/_app/recipes'
    | '/_app/reports'
    | '/_app/roles'
    | '/_app/stock-exports'
    | '/_app/suppliers'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock-exports': {
      id: '/_app/stock-exports'
      path: '/stock-exports'
      fullPath: '/stock-exports'
      preLoaderRoute: typeof AppStockExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes': {
      id: '/_app/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kiotviet': {
      id: '/_app/kiotviet'
      path: '/kiotviet'
      fullPath: '/kiotviet'
      preLoaderRoute: typeof AppKiotvietRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingredients': {
      id: '/_app/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof AppIngredientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingredient-usage': {
      id: '/_app/ingredient-usage'
      path: '/ingredient-usage'
      fullPath: '/ingredient-usage'
      preLoaderRoute: typeof AppIngredientUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-orders': {
      id: '/_app/import-orders'
      path: '/import-orders'
      fullPath: '/import-orders'
      preLoaderRoute: typeof AppImportOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImportOrdersRoute: typeof AppImportOrdersRoute
  AppIngredientUsageRoute: typeof AppIngredientUsageRoute
  AppIngredientsRoute: typeof AppIngredientsRoute
  AppKiotvietRoute: typeof AppKiotvietRoute
  AppRecipesRoute: typeof AppRecipesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppStockExportsRoute: typeof AppStockExportsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImportOrdersRoute: AppImportOrdersRoute,
  AppIngredientUsageRoute: AppIngredientUsageRoute,
  AppIngredientsRoute: AppIngredientsRoute,
  AppKiotvietRoute: AppKiotvietRoute,
  AppRecipesRoute: AppRecipesRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppStockExportsRoute: AppStockExportsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
