/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppStocktakeRouteImport } from './routes/_app/stocktake'
import { Route as AppStockExportsRouteImport } from './routes/_app/stock-exports'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRecipesRouteImport } from './routes/_app/recipes'
import { Route as AppPurchaseReturnsRouteImport } from './routes/_app/purchase-returns'
import { Route as AppProcessingRouteImport } from './routes/_app/processing'
import { Route as AppKiotvietRouteImport } from './routes/_app/kiotviet'
import { Route as AppIngredientsRouteImport } from './routes/_app/ingredients'
import { Route as AppIngredientUsageRouteImport } from './routes/_app/ingredient-usage'
import { Route as AppIngredientGroupsRouteImport } from './routes/_app/ingredient-groups'
import { Route as AppImportOrdersRouteImport } from './routes/_app/import-orders'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConsumptionVarianceRouteImport } from './routes/_app/consumption-variance'
import { Route as AppAuditLogsRouteImport } from './routes/_app/audit-logs'
import { Route as AppStocktakeIdRouteImport } from './routes/_app/stocktake_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStocktakeRoute = AppStocktakeRouteImport.update({
  id: '/stocktake',
  path: '/stocktake',
  getParentRoute: () => AppRoute,
} as any)
const AppStockExportsRoute = AppStockExportsRouteImport.update({
  id: '/stock-exports',
  path: '/stock-exports',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseReturnsRoute = AppPurchaseReturnsRouteImport.update({
  id: '/purchase-returns',
  path: '/purchase-returns',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessingRoute = AppProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AppRoute,
} as any)
const AppKiotvietRoute = AppKiotvietRouteImport.update({
  id: '/kiotviet',
  path: '/kiotviet',
  getParentRoute: () => AppRoute,
} as any)
const AppIngredientsRoute = AppIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AppRoute,
} as any)
const AppIngredientUsageRoute = AppIngredientUsageRouteImport.update({
  id: '/ingredient-usage',
  path: '/ingredient-usage',
  getParentRoute: () => AppRoute,
} as any)
const AppIngredientGroupsRoute = AppIngredientGroupsRouteImport.update({
  id: '/ingredient-groups',
  path: '/ingredient-groups',
  getParentRoute: () => AppRoute,
} as any)
const AppImportOrdersRoute = AppImportOrdersRouteImport.update({
  id: '/import-orders',
  path: '/import-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumptionVarianceRoute = AppConsumptionVarianceRouteImport.update({
  id: '/consumption-variance',
  path: '/consumption-variance',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppStocktakeIdRoute = AppStocktakeIdRouteImport.update({
  id: '/stocktake_/$id',
  path: '/stocktake/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/consumption-variance': typeof AppConsumptionVarianceRoute
  '/dashboard': typeof AppDashboardRoute
  '/import-orders': typeof AppImportOrdersRoute
  '/ingredient-groups': typeof AppIngredientGroupsRoute
  '/ingredient-usage': typeof AppIngredientUsageRoute
  '/ingredients': typeof AppIngredientsRoute
  '/kiotviet': typeof AppKiotvietRoute
  '/processing': typeof AppProcessingRoute
  '/purchase-returns': typeof AppPurchaseReturnsRoute
  '/recipes': typeof AppRecipesRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/stock-exports': typeof AppStockExportsRoute
  '/stocktake': typeof AppStocktakeRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
  '/stocktake/$id': typeof AppStocktakeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/consumption-variance': typeof AppConsumptionVarianceRoute
  '/dashboard': typeof AppDashboardRoute
  '/import-orders': typeof AppImportOrdersRoute
  '/ingredient-groups': typeof AppIngredientGroupsRoute
  '/ingredient-usage': typeof AppIngredientUsageRoute
  '/ingredients': typeof AppIngredientsRoute
  '/kiotviet': typeof AppKiotvietRoute
  '/processing': typeof AppProcessingRoute
  '/purchase-returns': typeof AppPurchaseReturnsRoute
  '/recipes': typeof AppRecipesRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/stock-exports': typeof AppStockExportsRoute
  '/stocktake': typeof AppStocktakeRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
  '/stocktake/$id': typeof AppStocktakeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/consumption-variance': typeof AppConsumptionVarianceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/import-orders': typeof AppImportOrdersRoute
  '/_app/ingredient-groups': typeof AppIngredientGroupsRoute
  '/_app/ingredient-usage': typeof AppIngredientUsageRoute
  '/_app/ingredients': typeof AppIngredientsRoute
  '/_app/kiotviet': typeof AppKiotvietRoute
  '/_app/processing': typeof AppProcessingRoute
  '/_app/purchase-returns': typeof AppPurchaseReturnsRoute
  '/_app/recipes': typeof AppRecipesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/stock-exports': typeof AppStockExportsRoute
  '/_app/stocktake': typeof AppStocktakeRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/stocktake_/$id': typeof AppStocktakeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/consumption-variance'
    | '/dashboard'
    | '/import-orders'
    | '/ingredient-groups'
    | '/ingredient-usage'
    | '/ingredients'
    | '/kiotviet'
    | '/processing'
    | '/purchase-returns'
    | '/recipes'
    | '/reports'
    | '/roles'
    | '/stock-exports'
    | '/stocktake'
    | '/suppliers'
    | '/users'
    | '/stocktake/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/consumption-variance'
    | '/dashboard'
    | '/import-orders'
    | '/ingredient-groups'
    | '/ingredient-usage'
    | '/ingredients'
    | '/kiotviet'
    | '/processing'
    | '/purchase-returns'
    | '/recipes'
    | '/reports'
    | '/roles'
    | '/stock-exports'
    | '/stocktake'
    | '/suppliers'
    | '/users'
    | '/stocktake/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/audit-logs'
    | '/_app/consumption-variance'
    | '/_app/dashboard'
    | '/_app/import-orders'
    | '/_app/ingredient-groups'
    | '/_app/ingredient-usage'
    | '/_app/ingredients'
    | '/_app/kiotviet'
    | '/_app/processing'
    | '/_app/purchase-returns'
    | '/_app/recipes'
    | '/_app/reports'
    | '/_app/roles'
    | '/_app/stock-exports'
    | '/_app/stocktake'
    | '/_app/suppliers'
    | '/_app/users'
    | '/_app/stocktake_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stocktake': {
      id: '/_app/stocktake'
      path: '/stocktake'
      fullPath: '/stocktake'
      preLoaderRoute: typeof AppStocktakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock-exports': {
      id: '/_app/stock-exports'
      path: '/stock-exports'
      fullPath: '/stock-exports'
      preLoaderRoute: typeof AppStockExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes': {
      id: '/_app/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-returns': {
      id: '/_app/purchase-returns'
      path: '/purchase-returns'
      fullPath: '/purchase-returns'
      preLoaderRoute: typeof AppPurchaseReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/processing': {
      id: '/_app/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof AppProcessingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kiotviet': {
      id: '/_app/kiotviet'
      path: '/kiotviet'
      fullPath: '/kiotviet'
      preLoaderRoute: typeof AppKiotvietRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingredients': {
      id: '/_app/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof AppIngredientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingredient-usage': {
      id: '/_app/ingredient-usage'
      path: '/ingredient-usage'
      fullPath: '/ingredient-usage'
      preLoaderRoute: typeof AppIngredientUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingredient-groups': {
      id: '/_app/ingredient-groups'
      path: '/ingredient-groups'
      fullPath: '/ingredient-groups'
      preLoaderRoute: typeof AppIngredientGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-orders': {
      id: '/_app/import-orders'
      path: '/import-orders'
      fullPath: '/import-orders'
      preLoaderRoute: typeof AppImportOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumption-variance': {
      id: '/_app/consumption-variance'
      path: '/consumption-variance'
      fullPath: '/consumption-variance'
      preLoaderRoute: typeof AppConsumptionVarianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stocktake_/$id': {
      id: '/_app/stocktake_/$id'
      path: '/stocktake/$id'
      fullPath: '/stocktake/$id'
      preLoaderRoute: typeof AppStocktakeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppConsumptionVarianceRoute: typeof AppConsumptionVarianceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImportOrdersRoute: typeof AppImportOrdersRoute
  AppIngredientGroupsRoute: typeof AppIngredientGroupsRoute
  AppIngredientUsageRoute: typeof AppIngredientUsageRoute
  AppIngredientsRoute: typeof AppIngredientsRoute
  AppKiotvietRoute: typeof AppKiotvietRoute
  AppProcessingRoute: typeof AppProcessingRoute
  AppPurchaseReturnsRoute: typeof AppPurchaseReturnsRoute
  AppRecipesRoute: typeof AppRecipesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppStockExportsRoute: typeof AppStockExportsRoute
  AppStocktakeRoute: typeof AppStocktakeRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppStocktakeIdRoute: typeof AppStocktakeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppConsumptionVarianceRoute: AppConsumptionVarianceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImportOrdersRoute: AppImportOrdersRoute,
  AppIngredientGroupsRoute: AppIngredientGroupsRoute,
  AppIngredientUsageRoute: AppIngredientUsageRoute,
  AppIngredientsRoute: AppIngredientsRoute,
  AppKiotvietRoute: AppKiotvietRoute,
  AppProcessingRoute: AppProcessingRoute,
  AppPurchaseReturnsRoute: AppPurchaseReturnsRoute,
  AppRecipesRoute: AppRecipesRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppStockExportsRoute: AppStockExportsRoute,
  AppStocktakeRoute: AppStocktakeRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUsersRoute: AppUsersRoute,
  AppStocktakeIdRoute: AppStocktakeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
