name: CI

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  TURBO_API: ${{ github.base_ref == 'develop' && 'http://127.0.0.1:8585' || '' }}
  TURBO_TEAM: ${{ github.base_ref == 'develop' && 'warehouse-management' || '' }}
  TURBO_TOKEN: ${{ github.base_ref == 'develop' && secrets.TURBO_TOKEN || '' }}

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Turborepo Remote Cache
        if: github.base_ref == 'develop'
        uses: brunojppb/turbo-cache-server@4.0.3
        env:
          PORT: "8585"
          OTEL_SDK_DISABLED: "true"
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          S3_BUCKET_NAME: ${{ secrets.TURBO_CACHE_BUCKET }}
          S3_REGION: "auto"
          S3_ACCESS_KEY: ${{ secrets.TURBO_CACHE_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.TURBO_CACHE_SECRET_KEY }}
          S3_ENDPOINT: ${{ secrets.TURBO_CACHE_ENDPOINT }}

      - run: npm ci

      - run: npx turbo lint

      - run: npx turbo test
